#!/bin/bash

for file in \
  AGMsseq.c ALMsseq.c Abasic.c Aclos.c Aclsseq.c Acompose.c Acrea.c Aenum.c \
  Ajoin.c Alamcm.c Alameq.c Alenmin.c Aload.c Amin.c Aopen.c Apowers.c \
  Aretape.c Asseq.c Astems.c Asubs.c Atrim.c Colon.c Lex.c O.h Parse.y \
  R.c S.c T.c U.c V.c local.h localc.h localh.h locals.h \
  stamp.c util.c y.tab.h
do
  expand < $file | astyle > $file.out
  mv $file.out $file
done
